version: '3'
services:
  ms_eureka:
    image: microservice/register:0.0.1-SNAPSHOT
    restart: always
    hostname: eureka-server
    ports:
      - "8761:8761"
    container_name: ms_eureka
    networks:
      - eureka-server
    env_file: ms.env
networks:
  eureka-server:
    external:
      name: ms_ms-net
