
spring:
  application:
    name: user-service
  datasource:
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/microservice
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
eureka:
  instance:
    hostname: 192.168.0.102
  client:
#    fetch-registry: true
#    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
server:
  port: 8750
#    service-url: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_PORT:8761}/eureka/